version: '3'

services:
  app:
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 && python setup.py"
    networks:
      - default
  bot:
    restart: always
    build:
      context: ./bot
    volumes:
      - ./bot:/bot
    command: >
      sh -c "python bot/BotManager.py"
    depends_on:
      - app
      - redis
      - initializer
    networks:
      - default
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    ports:
     - "6379:6379"
    networks:
      default:
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
  consumers:
    restart: always
    build:
      context: ./consumers
    volumes:
      - ./consumers:/consumers
    command: >
      sh -c "python redis/MessageConsumer.py"
    depends_on:
      - app
      - redis
      - initializer
    networks:
      - default
  initializer:
    build:
      context: ./initializer
    volumes:
      - ./initializer:/initializer
    command: >
      sh -c "python initializer/setup.py"
    depends_on:
      - app
    networks:
      - default
networks:
    default:
