# Generated by Django 3.1.4 on 2020-12-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201206_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processed_by_bot',
            field=models.BooleanField(default=False),
        ),
    ]
